import type { SiteMeta } from '@/types/site';

/**
 * Site-level metadata — the ONE place for deployment/branding settings; personal
 * content lives in `src/content/`.
 */
export const site: SiteMeta = {
  // Deployment HOST — keep in step with `SITE_URL` in `astro.config.mjs`. The
  // base path is separate (`src/utils/url.ts`): this is a GitHub Pages PROJECT
  // site, so pages live under `/naufalhamzah`. Drives canonical URLs, sitemap
  // and Open Graph tags.
  url: 'https://naufalhamzah.github.io',
  locale: 'en',
  /* A PNG, not SVG: no major link-preview scraper (Facebook, WhatsApp,
     LinkedIn, Slack, X) rasterises SVG, so an `.svg` here would never show.
     Generated by `node scripts/make-og.mjs` from the same data and tokens the
     site renders. */
  defaultOgImage: '/images/og-default.png',
};
